package tut01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T21:45:32.457+01:00
 * Generated source version: 3.5.11
 *
 */
@WebServiceClient(name = "WorkDistributorImplService",
                  wsdlLocation = "http://127.0.0.1:8000/WorkDistributor?wsdl",
                  targetNamespace = "http://tut01/")
public class WorkDistributorImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tut01/", "WorkDistributorImplService");
    public static final QName WorkDistributorImplPort = new QName("http://tut01/", "WorkDistributorImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8000/WorkDistributor?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkDistributorImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8000/WorkDistributor?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkDistributorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkDistributorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkDistributorImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WorkDistributorImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WorkDistributorImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WorkDistributorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WorkDistributor
     */
    @WebEndpoint(name = "WorkDistributorImplPort")
    public WorkDistributor getWorkDistributorImplPort() {
        return super.getPort(WorkDistributorImplPort, WorkDistributor.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkDistributor
     */
    @WebEndpoint(name = "WorkDistributorImplPort")
    public WorkDistributor getWorkDistributorImplPort(WebServiceFeature... features) {
        return super.getPort(WorkDistributorImplPort, WorkDistributor.class, features);
    }

}
