
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tut01;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T21:45:32.439+01:00
 * Generated source version: 3.5.11
 *
 */

@javax.jws.WebService(
                      serviceName = "WorkDistributorImplService",
                      portName = "WorkDistributorImplPort",
                      targetNamespace = "http://tut01/",
                      wsdlLocation = "http://127.0.0.1:8000/WorkDistributor?wsdl",
                      endpointInterface = "tut01.WorkDistributor")

public class WorkDistributorImplPortImpl implements WorkDistributor {

    private static final Logger LOG = Logger.getLogger(WorkDistributorImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#getPhoneNumberCurrentProgress(java.lang.String arg0)*
     */
    public tut01.PhoneNumberProgress getPhoneNumberCurrentProgress(java.lang.String arg0) {
        LOG.info("Executing operation getPhoneNumberCurrentProgress");
        System.out.println(arg0);
        try {
            tut01.PhoneNumberProgress _return = tut01.PhoneNumberProgress.IN_PROCESS;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#getEmployeeResponsibleForAssignment(java.lang.String arg0)*
     */
    public java.lang.String getEmployeeResponsibleForAssignment(java.lang.String arg0) {
        LOG.info("Executing operation getEmployeeResponsibleForAssignment");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-976808532";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#getListOfAssignedPhoneNumbers(java.lang.String arg0)*
     */
    public java.util.List<java.lang.String> getListOfAssignedPhoneNumbers(java.lang.String arg0) {
        LOG.info("Executing operation getListOfAssignedPhoneNumbers");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-486362662";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#setPhoneNumberCurrentProgress(java.lang.String arg0, tut01.PhoneNumberProgress arg1)*
     */
    public int setPhoneNumberCurrentProgress(java.lang.String arg0, tut01.PhoneNumberProgress arg1) {
        LOG.info("Executing operation setPhoneNumberCurrentProgress");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -1052488398;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#pushNewPhoneNumber(java.lang.String arg0, java.lang.String arg1, tut01.PhoneNumberMetadata arg2)*
     */
    public int pushNewPhoneNumber(java.lang.String arg0, java.lang.String arg1, tut01.PhoneNumberMetadata arg2) {
        LOG.info("Executing operation pushNewPhoneNumber");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = -262728145;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tut01.WorkDistributor#getMetadataForPhoneNumber(java.lang.String arg0)*
     */
    public tut01.PhoneNumberMetadata getMetadataForPhoneNumber(java.lang.String arg0) {
        LOG.info("Executing operation getMetadataForPhoneNumber");
        System.out.println(arg0);
        try {
            tut01.PhoneNumberMetadata _return = new tut01.PhoneNumberMetadata();
            _return.setPhoneNumber("PhoneNumber-1798805465");
            _return.setUserName("UserName-2104320053");
            _return.setCountryCode("CountryCode2038613672");
            _return.setApproximateLongitude(0.1186935771859281);
            _return.setApproximateLattitude(0.11278879607919645);
            _return.setApproximateYearlyIncomeInUSD(-5770281199926458013l);
            _return.setApproximateAge(-5328059648071270256l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
