
package tut01;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T21:45:32.376+01:00
 * Generated source version: 3.5.11
 *
 */
public final class WorkDistributor_WorkDistributorImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://tut01/", "WorkDistributorImplService");

    private WorkDistributor_WorkDistributorImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WorkDistributorImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WorkDistributorImplService ss = new WorkDistributorImplService(wsdlURL, SERVICE_NAME);
        WorkDistributor port = ss.getWorkDistributorImplPort();

        {
        System.out.println("Invoking getPhoneNumberCurrentProgress...");
        java.lang.String _getPhoneNumberCurrentProgress_arg0 = "1006637745";
        tut01.PhoneNumberProgress _getPhoneNumberCurrentProgress__return = port.getPhoneNumberCurrentProgress(_getPhoneNumberCurrentProgress_arg0);
        System.out.println("getPhoneNumberCurrentProgress.result=" + _getPhoneNumberCurrentProgress__return);


        }
        {
        System.out.println("Invoking getEmployeeResponsibleForAssignment...");
        java.lang.String _getEmployeeResponsibleForAssignment_arg0 = "1006637745";
        java.lang.String _getEmployeeResponsibleForAssignment__return = port.getEmployeeResponsibleForAssignment(_getEmployeeResponsibleForAssignment_arg0);
        System.out.println("getEmployeeResponsibleForAssignment.result=" + _getEmployeeResponsibleForAssignment__return);


        }
        {
        System.out.println("Invoking getListOfAssignedPhoneNumbers...");
        java.lang.String _getListOfAssignedPhoneNumbers_arg0 = "Satya_Nadella";
        java.util.List<java.lang.String> _getListOfAssignedPhoneNumbers__return = port.getListOfAssignedPhoneNumbers(_getListOfAssignedPhoneNumbers_arg0);
        System.out.println("getListOfAssignedPhoneNumbers.result=" + _getListOfAssignedPhoneNumbers__return);


        }
        {
        System.out.println("Invoking setPhoneNumberCurrentProgress...");
        java.lang.String _setPhoneNumberCurrentProgress_arg0 = "1006637745";
        tut01.PhoneNumberProgress _setPhoneNumberCurrentProgress_arg1 = tut01.PhoneNumberProgress.FAILED;
        int _setPhoneNumberCurrentProgress__return = port.setPhoneNumberCurrentProgress(_setPhoneNumberCurrentProgress_arg0, _setPhoneNumberCurrentProgress_arg1);
        System.out.println("setPhoneNumberCurrentProgress.result=" + _setPhoneNumberCurrentProgress__return);


        }
        {
        System.out.println("Invoking pushNewPhoneNumber...");
        java.lang.String _pushNewPhoneNumber_arg0 = "admin";
        java.lang.String _pushNewPhoneNumber_arg1 = "admin123";
        tut01.PhoneNumberMetadata _pushNewPhoneNumber_arg2 = new tut01.PhoneNumberMetadata();
        _pushNewPhoneNumber_arg2.setPhoneNumber("565645681668266");
        _pushNewPhoneNumber_arg2.setUserName("Hippolite");
        _pushNewPhoneNumber_arg2.setCountryCode("en-AU");
        _pushNewPhoneNumber_arg2.setApproximateLongitude(0.37043379157876466);
        _pushNewPhoneNumber_arg2.setApproximateLattitude(0.8466417113294915);
        _pushNewPhoneNumber_arg2.setApproximateYearlyIncomeInUSD(9999);
        _pushNewPhoneNumber_arg2.setApproximateAge(51);
        int _pushNewPhoneNumber__return = port.pushNewPhoneNumber(_pushNewPhoneNumber_arg0, _pushNewPhoneNumber_arg1, _pushNewPhoneNumber_arg2);
        System.out.println("pushNewPhoneNumber.result=" + _pushNewPhoneNumber__return);


        }
        {
        System.out.println("Invoking getMetadataForPhoneNumber...");
        java.lang.String _getMetadataForPhoneNumber_arg0 = "1006637745";
        tut01.PhoneNumberMetadata _getMetadataForPhoneNumber__return = port.getMetadataForPhoneNumber(_getMetadataForPhoneNumber_arg0);
        System.out.println("getMetadataForPhoneNumber.result=" + _getMetadataForPhoneNumber__return);


        }

        System.exit(0);
    }

}
