
package tut01.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.11
 * Wed Mar 26 22:07:14 CET 2025
 * Generated source version: 3.5.11
 */

@XmlRootElement(name = "getPhoneNumberCurrentProgressResponse", namespace = "http://tut01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPhoneNumberCurrentProgressResponse", namespace = "http://tut01/")

public class GetPhoneNumberCurrentProgressResponse {

    @XmlElement(name = "return")
    private tut01.PhoneNumberProgress _return;

    public tut01.PhoneNumberProgress getReturn() {
        return this._return;
    }

    public void setReturn(tut01.PhoneNumberProgress new_return)  {
        this._return = new_return;
    }

}

