
package tut01.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.11
 * Wed Mar 26 22:07:14 CET 2025
 * Generated source version: 3.5.11
 */

@XmlRootElement(name = "setPhoneNumberCurrentProgress", namespace = "http://tut01/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setPhoneNumberCurrentProgress", namespace = "http://tut01/", propOrder = {"arg0", "arg1"})

public class SetPhoneNumberCurrentProgress {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private tut01.PhoneNumberProgress arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public tut01.PhoneNumberProgress getArg1() {
        return this.arg1;
    }

    public void setArg1(tut01.PhoneNumberProgress newArg1)  {
        this.arg1 = newArg1;
    }

}

